### ISSUE TITLE
Mute microphone action

### ISSUE THREAD

**Issue by gerhardol** [ivaniskandar/shouko#11]
Feature suggestion

It would be nice to map the assistant key to a button.
In my case I would like to map it to the toggle mic button, https://developer.android.com/reference/android/view/KeyEvent#KEYCODE_MUTE
to control the Teams microphone.

It seems Tasker can do this though using volume keys, but not when the screen is off.

**Comment by ivaniskandar** [comment]
Not sure if I want to add customizable keycode here but I can add that mute button separately.
