### ISSUE TITLE
Support for Xperia 10 III model

### ISSUE THREAD

**Issue by malibcia** [ivaniskandar/shouko#12]
It would be awesome to have support for new Xperia models. Especially the one in the subject.

**Comment by ivaniskandar** [comment]
I don't have that device, but I can get you a test build if you're able to test. Just give me your device model number.

**Comment by deoma97** [comment]
I have the device and would absolutely love to have support for the 10 iii. The device model number is XQ-BT52

**Comment by malibcia** [comment]
Yup, Model: XQ-BT52
Happy to test too!

czw., 8 lip 2021, 16:23 użytkownik deoma97 ***@***.***>
napisał:

**Comment by ivaniskandar** [comment]
@deoma97 @malibcia get the artifact here https://github.com/ivaniskandar/shouko/actions/runs/1013924298

**Comment by malibcia** [comment]
I have just tried, and:
- on unlocked screen it launches selected app right away,
- on locked it launches assistant and right after the selected app, assistant stays in the background,
All as expected?

As my launching app I did try: camera, telegram, calendar, qr scanner - for each it behave in the same way.

**Comment by ivaniskandar** [comment]
> I have just tried, and:
> 
> * on unlocked screen it launches selected app right away,
> * on locked it launches assistant and right after the selected app, assistant stays in the background,
> 
> All as expected?
> 
> As my launching app I did try: camera, telegram, calendar, qr scanner - for each it behave in the same way.

Yes it's a bit tricky with locked screen. The current behavior is the best I can do so far.

**Comment by malibcia** [comment]
I am still very happy. Thank you.
