### ISSUE TITLE
Does XPERI+ support map assistant button to complicated actions?

### ISSUE THREAD

**Issue by ldzhjn** [ivaniskandar/shouko#14]
For example I want to set the assistant key's behavior as follows:
double click - cycle flashlight open/close
single click - cycle through sound/vibration/mute
long click - take screenshot

**Comment by ivaniskandar** [comment]
Due to how the app detect the button events, long press action is not possible. Double click should be possible but single click detection is slow (and wonky) enough so I didn't bother implementing the double click detection.
