### ISSUE TITLE
If I mapped the assistant button to flashlight action, can flashlight be opened in locked state?

### ISSUE THREAD

**Issue by ldzhjn** [ivaniskandar/shouko#15]
From the comments in GAKeyOverrider.kt, it states
 * When it runs on locked state, [GAKeyOverriderKeyguardActivity]
 * will be called first to request unlock and launches the custom
 * action when user unlock completed.
If I mapped the assistant button to flashlight action, it looks like the flashlight can only be opened after unlocking.
Please confirm if my understanding is correct.

**Comment by ivaniskandar** [comment]
The keyguard unlock is only needed to launch app intent as stated [here](https://github.com/ivaniskandar/shouko/blob/master/app/src/main/java/xyz/ivaniskandar/shouko/feature/GAKeyOverrider.kt#L249), other actions will run immediately.
