### ISSUE TITLE
Support for Xperia 1 III

### ISSUE THREAD

**Issue by TheNetAdmin** [ivaniskandar/shouko#16]
I noticed #12 and would like to help test assistant button remap on my Xperia 1 III.

My device model number is XQ-BC62.

BTW this project is cool!

**Comment by ivaniskandar** [comment]
That commit doesn't have your XQ-BC62 model so you need to add that first.

**Comment by TheNetAdmin** [comment]
> That commit doesn't have your XQ-BC62 model so you need to add that first.

Oh didn't notice that was XQ-BC72, will try with the correct model

**Comment by andreidobrica** [comment]
I would like to test also, please.
My model is XQ-BC52.
Can you add also this model to the list?

**Comment by TheNetAdmin** [comment]
> I would like to test also, please.
> My model is XQ-BC52.
> Can you add also this model to the list?

I need to register a sign key to build the app in GitHub CI. May not have time these days, but will update the progress here once I successfully build the app.

**Comment by CossieLover1369** [comment]
Is there a link to a version of this app which works on Xperia 1 iii please, exact model is XQ-BC52. Sorry if this seems a stupid question not very experienced with this site. Many thanks

**Comment by TheNetAdmin** [comment]
> Is there a link to a version of this app which works on Xperia 1 iii please, exact model is XQ-BC52. Sorry if this seems a stupid question not very experienced with this site. Many thanks

Try [this](https://github.com/TheNetAdmin/shouko/actions/runs/1186864825) before #17 is added to this main rrpo
