### ISSUE TITLE
Not working on 5ii when Google app is removed.

### ISSUE THREAD

**Issue by jxosborne** [ivaniskandar/shouko#18]
Hello,

I just discovered this app and was so excited! unfortunately it doesn't seem to be working any longer, I see a few people on your reddit post are having the same issue.

Details:

Build: 58.1.A.5.330
Root: Systemless with Magisk 23
SafetyNet: Passes

This phone was freshly reset just today, and I've removed most of the google bloatware through adb and package manager.  This includes the Google Assistant app.

Google Play Services is still installed, and the core google framework remains in place.  I've tried reinstalling the Assistant app, as well as the Google app and this had no affect

Any idea why this wouldn't be working?

Thanks!

**Comment by ivaniskandar** [comment]
I have the same firmware version and it's working fine. I believe you removed something that breaks the thing that this app needs to detect the button press.

**Comment by jxosborne** [comment]
I figured that, yeah.

Any idea at all what it could be?

I'll start adding back things one by one and see if I can figure it out and post back here for the next guy that comes along with the same problem.

**Comment by ivaniskandar** [comment]
Honestly I can only think of the Google app and Google Assistant, if that works then the app _should_ work.

**Comment by jxosborne** [comment]
Figured it out:

com.google.android.googlequicksearchbox, which as you guessed is the Google app.  Don't need the assistant app at all.

I notice that the Google app does appear very briefly when the button is pressed, than it disappears and the app I've selected pops up.  I assume that means you are watching for that event to be fired, cancelling it and replacing it with the new app?  Maybe it would be possible to watch for the call to com.google.android.googlequicksearchbox, and cancel it before it ever happens; this would probably fix the issue with the button not working when the app is not installed.

It would likely stop that brief pop up of the Google App as well.

**Comment by ivaniskandar** [comment]
I can try to modify the code but I need a logcat when you push the assistant button while the google app isn't installed.

**Comment by jxosborne** [comment]
Hi Ivan,

Here is an extract from the moment I press the assistant key without the Google app installed, let me know if there is anything I can help with:

09-07 09:54:43.801  1709  1740 I GAKeyEventHandler: launchAssistGuideActivity
09-07 09:54:43.802  1709  1740 I ActivityTaskManager: START u0 {flg=0x10000000 cmp=com.google.android.googlequicksearchbox/com.google.android.apps.gsa.staticplugins.opa.EnterOpaActivityFromDeeplink} from uid 1000
09-07 09:54:43.804  1709  1742 D EventSequenceValidator: IntentStarted during UNKNOWN. Intent { flg=0x10000000 cmp=com.google.android.googlequicksearchbox/com.google.android.apps.gsa.staticplugins.opa.EnterOpaActivityFromDeeplink }
09-07 09:54:43.804  1709  1742 D EventSequenceValidator: java.lang.Throwable: EventSequenceValidator#getStackTrace
09-07 09:54:43.804  1709  1742 D EventSequenceValidator:        at com.google.android.startop.iorap.EventSequenceValidator.logWarningWithStackTrace(EventSequenceValidator.java:260)
09-07 09:54:43.804  1709  1742 D EventSequenceValidator:        at com.google.android.startop.iorap.EventSequenceValidator.onIntentStarted(EventSequenceValidator.java:106)
09-07 09:54:43.804  1709  1742 D EventSequenceValidator:        at com.android.server.wm.LaunchObserverRegistryImpl.handleOnIntentStarted(LaunchObserverRegistryImpl.java:139)
09-07 09:54:43.804  1709  1742 D EventSequenceValidator:        at com.android.server.wm.LaunchObserverRegistryImpl.lambda$veRn_GhgLZLlOHOJ0ZYT6KcfYqo(Unknown Source:0)
09-07 09:54:43.804  1709  1742 D EventSequenceValidator:        at com.android.server.wm.-$$Lambda$LaunchObserverRegistryImpl$veRn_GhgLZLlOHOJ0ZYT6KcfYqo.accept(Unknown Source:10)
09-07 09:54:43.804  1709  1742 D EventSequenceValidator:        at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:292)
09-07 09:54:43.804  1709  1742 D EventSequenceValidator:        at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
09-07 09:54:43.804  1709  1742 D EventSequenceValidator:        at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
09-07 09:54:43.804  1709  1742 D EventSequenceValidator:        at android.os.Handler.handleCallback(Handler.java:938)
09-07 09:54:43.804  1709  1742 D EventSequenceValidator:        at android.os.Handler.dispatchMessage(Handler.java:99)
09-07 09:54:43.804  1709  1742 D EventSequenceValidator:        at android.os.Looper.loop(Looper.java:368)
09-07 09:54:43.804  1709  1742 D EventSequenceValidator:        at android.os.HandlerThread.run(HandlerThread.java:67)
09-07 09:54:43.804  1709  1742 D EventSequenceValidator:        at com.android.server.ServiceThread.run(ServiceThread.java:44)
09-07 09:54:43.804  1709  1742 D EventSequenceValidator: inc AccIntentStartedEvents to 2
09-07 09:54:43.805  1709  1742 D EventSequenceValidator: onIntentFailed during UNKNOWN.
09-07 09:54:43.805  1709  1742 D EventSequenceValidator: java.lang.Throwable: EventSequenceValidator#getStackTrace
09-07 09:54:43.805  1709  1742 D EventSequenceValidator:        at com.google.android.startop.iorap.EventSequenceValidator.logWarningWithStackTrace(EventSequenceValidator.java:260)
09-07 09:54:43.805  1709  1742 D EventSequenceValidator:        at com.google.android.startop.iorap.EventSequenceValidator.onIntentFailed(EventSequenceValidator.java:130)
09-07 09:54:43.805  1709  1742 D EventSequenceValidator:        at com.android.server.wm.LaunchObserverRegistryImpl.handleOnIntentFailed(LaunchObserverRegistryImpl.java:147)
09-07 09:54:43.805  1709  1742 D EventSequenceValidator:        at com.android.server.wm.LaunchObserverRegistryImpl.lambda$KukKmVpn5W_1xSV6Dnp8wW2H2Ks(Unknown Source:0)
09-07 09:54:43.805  1709  1742 D EventSequenceValidator:        at com.android.server.wm.-$$Lambda$LaunchObserverRegistryImpl$KukKmVpn5W_1xSV6Dnp8wW2H2Ks.accept(Unknown Source:2)
09-07 09:54:43.805  1709  1742 D EventSequenceValidator:        at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:264)
09-07 09:54:43.805  1709  1742 D EventSequenceValidator:        at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
09-07 09:54:43.805  1709  1742 D EventSequenceValidator:        at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
09-07 09:54:43.805  1709  1742 D EventSequenceValidator:        at android.os.Handler.handleCallback(Handler.java:938)
09-07 09:54:43.805  1709  1742 D EventSequenceValidator:        at android.os.Handler.dispatchMessage(Handler.java:99)
09-07 09:54:43.805  1709  1742 D EventSequenceValidator:        at android.os.Looper.loop(Looper.java:368)
09-07 09:54:43.805  1709  1742 D EventSequenceValidator:        at android.os.HandlerThread.run(HandlerThread.java:67)
09-07 09:54:43.805  1709  1742 D EventSequenceValidator:        at com.android.server.ServiceThread.run(ServiceThread.java:44)
09-07 09:54:43.805  1709  1742 D EventSequenceValidator: dec AccIntentStartedEvents to 1

**Comment by ivaniskandar** [comment]
Please get [this build](https://github.com/ivaniskandar/shouko/actions/runs/1211924290) and see if it works for you.

**Comment by jxosborne** [comment]
Thanks Ivan,

It works perfectly.  It is also looks much nicer without that brief 
popup from the google app!

Something to note for the release, which I'm sure you already knew:  
This works ONLY if the google app is fully uninstalled via adb.  If the 
Google app is only disabled, this doesn't work at all.

**Comment by jxosborne** [comment]
Absolutely nothing.  I'll grab a logcat for you later today if you'd like.

**Comment by ivaniskandar** [comment]
It's okay, you can try [this build](https://github.com/ivaniskandar/shouko/actions/runs/1214422075) when it's done compiling.

**Comment by jxosborne** [comment]
Working perfectly now in all 3 states:

🗸 Google app installed.
🗸 Google app disabled.
🗸 Google app uninstalled. 

Thanks so much for correcting that so quickly!
