### ISSUE TITLE
Cannot map Yandex assistant to Assistant button

### ISSUE THREAD

**Issue by czukowski** [ivaniskandar/shouko#22]
I wanted to try mapping Yandex assistant (Алиса) to the Assistant button, I can see there is a shortcut for it in the list, but when I click it, the list is closed as if the action has been accepted, but the Custom action is not changed and still shows the previous selection. In fact that was the only shortcut I could see behave this way, so there's probably something wrong with the shortcut and not your app.

Do you have any idea what's wrong with it though?

**Comment by ivaniskandar** [comment]
Where can I download this app?

**Comment by czukowski** [comment]
@ivaniskandar thanks for looking into it.

This is the app: https://play.google.com/store/apps/details?id=ru.yandex.searchplugin

A shortcut has an icon looking like this: https://avatars.mds.yandex.net/get-lpc/1364677/29c47d98-903f-492f-b029-f15fcbd65962/width_1600x2

**Comment by ivaniskandar** [comment]
It looks like the Alice shortcut is made using a newer API that's not readable by non-launcher app.

But fret not, I'll add a "Digital Assistant" action so you can just set the Digital Assistant app to Yandex in system settings instead.
