### ISSUE TITLE
Google assistant still showing

### ISSUE THREAD

**Issue by vvinx13** [ivaniskandar/shouko#23]
Often the button press acts gimmicky. Sometimes it doesn't react, sometimes it opens Google assistant settings asking me if I want to change it.
Default apps on locked screen appear then disappear. Wanted to change back and I can't. Icons look different now and the old ones appear then disappear again.

**Comment by ivaniskandar** [comment]
The button will not trigger if you press it too quickly. For trigger on locked screen, the assistant app will show longer than when on unlocked screen and it's just the way this feature works.

**Comment by vvinx13** [comment]
thanks for clarifying it
cheers and keep up the good work
