### ISSUE TITLE
Remap Assistant Button not work in 0.6.0 on Sony Xperia 1III without Google Assistant pre-installed

### ISSUE THREAD

**Issue by minipanda** [ivaniskandar/shouko#25]
Hello, Ivan. I just installed this App from Reddit recommendation.
after enabled required permissions from adb shell, when pressing down the assistant key, it still jump out "Default digital assistant app" but not the App I set. Is there any way I can trace further to provide more details for debug?
currently I only gathered the following from logcat:

11-02 04:26:15.439  1198  3178 E FrameEvents: addQueue: but current frame has not composited!
11-02 04:26:15.524  1287  2063 I GAKeyEventHandler: launchDefaultAssistSettings Intent { act=android.intent.action.MANAGE_DEFAULT_APP cat=[android.intent.category.DEFAULT] flg=0x10000000 (has extras) }
11-02 04:26:15.505  1198  3178 I chatty  : uid=1000(system) Binder:1198_5 identical 14 lines
11-02 04:26:15.513  1198  3178 E FrameEvents: addQueue: but current frame has not composited!
11-02 04:26:15.526  1287  1405 D EventSequenceValidator: Transition from INTENT_FAILED to INTENT_STARTED
11-02 04:26:15.526  1287  2063 I ActivityTaskManager: START u0 {act=android.intent.action.MANAGE_DEFAULT_APP cat=[android.intent.category.DEFAULT] flg=0x10000000 cmp=com.google.android.permissioncontroller/com.android.permissioncontroller.role.ui.DefaultAppActivity (has extras)} from uid 1000

BTW: It's a Sony Xepria III Model: XQ-BC72, Build number: 61.0.A.15.27 release-keys. by default not come with Google Assistant preinstalled.

**Comment by ivaniskandar** [comment]
Thanks for the report! Please try the canary build when it's done building.
