### ISSUE TITLE
Support for Moto G 5g

### ISSUE THREAD

**Issue by atharvbadkas** [ivaniskandar/shouko#27]
Hello,
Nice work!

Can remapping assistant button on moto G 5g achieved using this app?
Currently running on Android 11.

Thanks

**Comment by ivaniskandar** [comment]
The detection is currently specific for Sony firmware. I don't have a Moto G 5G to test so feel free to contribute.

**Comment by atharvbadkas** [comment]
I don't much know about Java but I can test it for you and provide log files if needed
