### ISSUE TITLE
Please support Xperia 1 iii XQ-BC42

### ISSUE THREAD

**Issue by XeNO1827** [ivaniskandar/shouko#31]
https://www.sony.jp/xperia-sp/products/XQ-BC42/

This model number was released in Japan in 19 November.
Installed and working, but Assistant Button remap is not working.

**Comment by XeNO1827** [comment]
Thank you!
I'm looking forward to the new version!

**Comment by ivaniskandar** [comment]
You can get the canary build here https://github.com/ivaniskandar/shouko/suites/4579777229/artifacts/123337233

**Comment by XeNO1827** [comment]
Great, I successfully remapped it!
By the way, I see the behavior that Google assistant starts for a moment and then closes immediately, is this normal behavior?

https://user-images.githubusercontent.com/95573044/145051735-8bb0a2db-6f30-4ba9-a320-55a3d7b221c5.mp4

**Comment by ivaniskandar** [comment]
Yes it's normal since the app can't completely replace the assistant.

**Comment by XeNO1827** [comment]
Thanks for the reply.
I'll be using your great app.
