### ISSUE TITLE
Remap Assistant Button works in 0.6.1 but still shows the "Choose digital Assistant" Popup you get if you have no Assistant selected

### ISSUE THREAD

**Issue by pandavova** [ivaniskandar/shouko#32]
Sony Xperia II - XQ-AS52
Android 11, 58.1.A.5.474

Continuation of #25, in my Case I uninstalled the Google Assistant from my Phone. It would be nice if you figure this out by not showing the popup instead of putting a dummy app as the assistant. For example long pressing the home button could trigger the assistant, and that would trigger the imaginary dummy app, wouldn't be nice.

Sometimes when selecting some functions my (media) audio volume gets set muted or pauses my current playback (yt video). Really weird.

**Comment by ivaniskandar** [comment]
The system shows a popup to reenable Google Assistant and this app can't fully disable it.

Regarding muted audio volume, you can disable the "Hide Assistant sound cue" settings.
