### ISSUE TITLE
Incorrect on screen instructions

### ISSUE THREAD

**Issue by thelyo** [ivaniskandar/shouko#33]
Currently reads : "adb shell pm grant xyz.ivaniskandar.shouko android.permission.WRITE_SECURE_SETTING"

Should read : "adb shell pm grant xyz.ivaniskandar.shouko android.permission.WRITE_SECURE_SETTINGS"

Note final "S"

**Comment by ivaniskandar** [comment]
Please send a screenshot showing the incorrect command line
