### ISSUE TITLE
Not have Assistant Button option,what's to be done？

### ISSUE THREAD

**Issue by WangHoo** [ivaniskandar/shouko#35]
![Screenshot_20220114-224157](https://user-images.githubusercontent.com/24491119/149533699-518fa389-ae79-44fb-baaf-2b4e4fbe750b.png)
My mobile phone model is XQ-AS72 XPERIA5Ⅱ Taiwan edition

**Comment by ivaniskandar** [comment]
Try the canary version https://github.com/ivaniskandar/shouko/suites/4851144268/artifacts/137764118

**Comment by WangHoo** [comment]
> 试试金丝雀版本https://github.com/ivaniskandar/shouko/suites/4851144268/artifacts/137764118

![Screenshot_20220115-043332](https://user-images.githubusercontent.com/24491119/149581516-93143e18-8f13-4d31-8191-9d71287fef04.png)
The problem still exists, two weeks ago I used version 0.6.0 without problems, but then I unlocked the phone bl and rooted it, and now I can't see the option to set the button.

**Comment by WangHoo** [comment]
> Try the canary version https://github.com/ivaniskandar/shouko/suites/4851144268/artifacts/137764118

Now my phone status Android11, rooted, unlocked

**Comment by ivaniskandar** [comment]
If you're using a root module to spoof model number then you will need to disable it first.

**Comment by WangHoo** [comment]
> 

Wow!  Thank you, I didn't even think that I have modified the model of the mobile phone, this should be the problem, after I turn off the module that modifies the model.  I'll let you know if it works.

**Comment by WangHoo** [comment]
> If you're using a root module to spoof model number then you will need to disable it first.

It's available now, thank you again
