### ISSUE TITLE
Using assistant button now mutes media audio on Android 12

### ISSUE THREAD

**Issue by Snakespeare415** [ivaniskandar/shouko#37]
I've had the assistant button mapped to flashlight without issue. After updating to Android 12 on Xperia 1 III (XQ-BC52) pressing it activates flashlight but also mutes media. Pressing it again does not unmute. Any idea what causes this issue?

**Comment by ivaniskandar** [comment]
You can disable the "Hide Assistant sound cue" if it doesn't work properly on your device.
