### ISSUE TITLE
when reboot device the asistant button action not work

### ISSUE THREAD

**Issue by nuborisar** [ivaniskandar/shouko#39]
Thanks for the application, but I had a problem, when you restart the device, the action of the assistant button stops working and you have to open the application again.
I have added a receiver to restart the service after the reboot.

https://github.com/nuborisar/shouko/tree/reboot

**Comment by ivaniskandar** [comment]
TadanoTileParentService is not the assistant button service. And the assistant button feature is run by an accessibility service which started automatically by the system.
