### ISSUE TITLE
Assistant button does nothing if overridden on Andioid 12

### ISSUE THREAD

**Issue by vozhyk-** [ivaniskandar/shouko#41]
After upgrading my Xperia 5 II XQ-AS52 to Android 12 (58.2.A.0.899), when I hold the assistant button, nothing happens. I get the same results after upgraging to Xperi+ 0.7.0.

I tried this with the action set to Play/Pause or starting an application.
If I reset the override setting to default, Google Assistant shows up when I press the button.

**Comment by TheWaschtlPlays** [comment]
Same here. But strangely on my Xperia 1 III it also didn't work on Android 11.

**Comment by ivaniskandar** [comment]
I haven't got the update yet so I'll take a look when I get it.

**Comment by liuhuoz** [comment]
> 

Same problem on Xperia 1 III and Android 11(61.0.A.23.60). I changed recent 3 versions and still have the bug

**Comment by dreDREb13** [comment]
Also same issue, but the remap worked on fine on Android 12 (61.1.A.2.211) on my 5 III with the last version (0.6.1). Updating to 0.7.0 has made it not work.

I did adb uninstall the assistant and pretty much every Google app after setting it up though. Worked fine after, but not sure if it depends on something in the app for the initial set up and this update killed that for me?

**Comment by ivaniskandar** [comment]
Fix is implemented in 0.7.1

**Comment by TheWaschtlPlays** [comment]
Yes i can confirm that it is working on my Xperia 1 III running Android 12 (61.1.A.2.221)
BUT... it always opens the assistent window aswell.. is there any way to fix that?

**Comment by ivaniskandar** [comment]
It's just the way how the feature works. You can disable Google app to completely hide Assistant window.
