### ISSUE TITLE
Upgrading to 0.7.0 fail on Xperia 5ii Android 12

### ISSUE THREAD

**Issue by jasonycw** [ivaniskandar/shouko#43]
I have recently upgrade my 5ii to Android 12 and the old version, 0.6.1, is still working fine.

However, when I install 0.7.0, the app fail to acknowledge the accessibility service, re-enable it cause the app to force close on launch.

**Comment by ivaniskandar** [comment]
Please you try checking if downgrading back to previous version fix the issue

**Comment by jasonycw** [comment]
Yes, I need to uninstall the latest version of the app and reinstall the previous version then do the permission adb command again to make it work.

**Comment by ivaniskandar** [comment]
Fix is implemented in 0.7.1

**Comment by GvY85** [comment]
Hi, sorry but it still does not work. Was about to write a ticket when I saw 0.7.1 released so did a fresh install but lo luck

**Comment by GvY85** [comment]
nvm, had to toggle the feature on and off for it to work
