### ISSUE TITLE
Play/pause remap doesn't work correctly

### ISSUE THREAD

**Issue by MelonHell** [ivaniskandar/shouko#48]
I want to remap assistant button to play/pause, and I've found a few problems:
1) The pause does not always work.
2) The screen wakes up, which is not desirable
3) Conflicts with Accidental Touch Prevention
4) I would like double and triple tap to navigate music

And my assistant continues to pop up for one second

Xperia 5 II XQ-AS52
Android 12 stock (with magisk)

UPD. Disabling the Google app helps get rid of the pop-up assistant. It also solves problems 1 and 3.

**Comment by ivaniskandar** [comment]
Due to how the button is handled, the app can only "override" the button that's why the Assistant is always showing briefly and the screen will be turned on when the button is pressed.
