### ISSUE TITLE
Assistant Button rebind to Screenshot 

### ISSUE THREAD

**Issue by sakonull** [ivaniskandar/shouko#50]
When rebinding the assistant button to take a screenshot google assistant shows up for a second. It appears in the screenshot every time.

**Comment by ivaniskandar** [comment]
The assistant will popup briefly after you press the button and the screenshot should fire after the popup is closed. Or is it still opens for you?

**Comment by sakonull** [comment]
I figured this out months ago but I want to leave info for anyone looking. You just need to disable the google and google assistant app. Then you can bind the physical assistant button to whatever you want without issue.
