### ISSUE TITLE
Possibility? Map enable/disable Accessibility Service to Google assist button

### ISSUE THREAD

**Issue by Son-Vegitto** [ivaniskandar/shouko#52]
Hello,

Under Android 11, there is an OS bug related to Controller input, which is only fixed by disabling certain Accessable services. So, would it be possible to map the Google assist button to toggle a specific Accessibility service?

Thanks!

**Comment by ivaniskandar** [comment]
Unfortunately it is not possible to disable or enable another accessibility service.
