### ISSUE TITLE
Android 12 support?

### ISSUE THREAD

**Issue by garrigue** [ivaniskandar/shouko#56]
I installed the app on an Android 12 xperia 5 iii, giving the permissions though adb as explained, but no button appears on the screen to modify the Google assistant button. The other functionalities seem to work.
Is this a known problem?
![Screenshot_20220727-135414](https://user-images.githubusercontent.com/870242/181164485-e93179a8-9a5a-4cb0-aa7d-d4d0aeccb37e.png)

**Comment by ivaniskandar** [comment]
Try the canary build [here](https://github.com/ivaniskandar/shouko/suites/7598782877/artifacts/314976515)

**Comment by garrigue** [comment]
Thanks!
This works perfectly.

**Comment by garrigue** [comment]
Actually, I'm not sure whether it is specific to Android 12, but GA appears not to be inhibited. That is, if I set another application to the GA button, that application is indeed activated, but when I go back to my home screen, the GA is waiting for me...
