### ISSUE TITLE
Play/Pause no longer works after XX minutes if left paused

### ISSUE THREAD

**Issue by velcrosnake** [ivaniskandar/shouko#58]
I was wondering if anyone else had this issue:

I'm using Pocket Casts to play podcasts and the Play/Pause media functionality works fine initially, but if I pause a podcast and leave it paused for too long, hitting the button will no longer play the audio unless I go back into the Pocket Casts app (which is still showing in my recent apps) and hit Play manually, then the media button functions normally again. (until the next time I leave it not playing for too long.

I know it's still detecting the button press, because hitting the button wakes up my screen just like it would when the Play/Pause function is working, it just doesn't play anymore.

I'm wondering if maybe this is Android 12 being too aggressive with shutting down app services in the background after they haven't been used for a while? Kinda like how in Android 10 the media controls would show on my lock screen and notifications indefinitely when I had them paused, but with Android 11 and 12 they go away after a few minutes when paused.

**Comment by ivaniskandar** [comment]
You can try pressing the play button of the media control in notification pane first. If it doesn't work or doesn't available then it will not work with the remap button too.

**Comment by velcrosnake** [comment]
Well, at the point the media control still shows as active the remapped Google Assistant button still works. I guess the issue is that with Android 12 (and 11), the Media Control goes away from the lock screen and the Notification panel after a while. The remapped Google Assistant button will still work normally as a Play/Pause for some time after that, but if enough time is passed then it won't work anymore.

I guess it might just be an Android 11/12 thing then, as with Android 10 (with my Samsung S10e and the Bixby button remapped) I could leave a podcast paused for days and the media Control would stay on the Lock Screen and Notifications as long as the player was active, as well as the Play/Pause functionality working fine. I am guessing if I downgraded the Xperia to Android 10 it would probably work without issue.

(also makes me think if I get the Zenfone 9 because it has media button functionality built in I might be disappointed when it has the same issue)
