### ISSUE TITLE
Permissions not detected on xperia 5 III

### ISSUE THREAD

**Issue by Hoiitsme** [ivaniskandar/shouko#60]
adb shell was used to add both READ_LOGS and WRITE_SECURE_SETTINGS permissions.
The sysdump of the package confirmed that the permission is granted, but app does not seem to actually have the permissions.
Restart did not work.

**Comment by ivaniskandar** [comment]
Try the canary version https://github.com/ivaniskandar/shouko/suites/7598782877/artifacts/314976515
