### ISSUE TITLE
[Feature Request] Add to custom roms

### ISSUE THREAD

**Issue by SpectreDev1** [ivaniskandar/shouko#63]
If you could help me we can add this to Custom ROM device trees and this will come standard on all ROMs, what do you think

**Comment by ivaniskandar** [comment]
I'm sure with custom rom you can directly tap into the button handler so this app shouldn't be needed, but I'm down with helping in anyway I can.

**Comment by SpectreDev-007** [comment]
Yeah before we do that have an issue the button mapping doesn't work on A13 for some reason
