### ISSUE TITLE
Google Assistant no longer makes a sound

### ISSUE THREAD

**Issue by russianspy1234** [ivaniskandar/shouko#68]
So I was playing around with this, and remapped the button to something else, and used the setting to suppress the google audio stream.  The issue is, I seem to be unable to revert this because I decided I like the assistant button after all.  I changed the settings back to default, and even tried uninstalling the APK, and now my google assistant still doesn't make a sound, even if I launch it by holding the home button.

**Comment by ivaniskandar** [comment]
This app only briefly mute the media volume so it's not related but Assistant only makes sound if one or more accessibility service is enabled.
