### ISSUE TITLE
Set Google assistant as power button.

### ISSUE THREAD

**Issue by AliOfHashemi** [ivaniskandar/shouko#77]
Can you add the ability to next update that use Google Assistant in the hold power button after remapping?

**Comment by ivaniskandar** [comment]
I'm sorry but emulating power button is impossible

**Comment by AliOfHashemi** [comment]
So is it possible to add ability as hold or double click assistant button for google assistant?
For example if the click assistant button turn the flash light on or if hold the button for start google assistant or double click for do other things.
