### ISSUE TITLE
Assistant Button Override not working

### ISSUE THREAD

**Issue by kako774** [ivaniskandar/shouko#9]
I have manually granted READ_LOGS and WRITE_SECURE_SETTINGS permissions in ADB, but I can't get it to work on my Xperia 5 II XQ-AS42 (Android 11).
In 0.2.0, such items do not appear in the first place.
In 0.1.1, the item appears, but it says not supported.

**Comment by ivaniskandar** [comment]
You have the new 5 II model, get the canary build until new version is released. The link is in readme.

**Comment by kako774** [comment]
Thank you. It worked fine.
